#get targets (определяем директорию)
#prepare build (определяем аргументы директории, название итогового файла)
#build (компилируем ЛаТеХ)
#upload (загружаем обратно с нужным именем)

# "ИмяЛектора_Предмет_Семестр" !!!!!

name: build and upload latex

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: get target
        id: get-target
        run: |
          FULL_PATH=semester_2/algebra_dyomin
          echo "FULL_PATH=$(echo ${FULL_PATH})" >> $GITHUB_ENV
          LECTURE_NAME=Dyomin_Algebra_2
          echo "LECTURE_NAME=$(echo ${LECTURE_NAME})" >> $GITHUB_ENV
         
      - name: Build
        id: build
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          working_directory: ${{ env.FULL_PATH }}
          args: -jobname=${{ env.LECTURE_NAME}} -pdf -file-line-error -halt-on-error -interaction=nonstopmode
          compiler: latexmk
          
      - name: upload pdf document
        uses: actions/upload-artifact@v2
        with:
           name: ${{ env.LECTURE_NAME}}.pdf
           path: ${{ env.FULL_PATH}}/${{ env.LECTURE_NAME}}.pdf
  
