name: Build and deploy LaTeX
on:
    push:
        branches:
            - '!master'

jobs:
    prepare:
        - name: get target
          id: get-target
          run: |
            export BRANCH=${GITHUB_REF#refs/heads/}
            python -c '
            import json
            import os
            targets = json.load(open("config.json", "r"))[os.environ["BRANCH"]]
            print("::set-output name=matrix::[", ", ".join(repr(t) for t in targets), "]", sep="")
            '
    build:
        runs-on: ubuntu-latest
            steps:
                         
                        - uses: actions/checkout@v2

                        - name: PrepareBuild
                          run: |
                                  pwd
                                  mkdir raw_build
                                  BRANCH_NAME=${GITHUB_REF#refs/heads/}
                                  echo "BRANCH_NAME=$(echo ${BRANCH_NAME})" >> $GITHUB_ENV
                                  BRANCH_ARGUMENTS=(${BRANCH_NAME//\// })
                                  SEMESTER=${BRANCH_ARGUMENTS[0]}
                                  CONSPECT_NAME=${BRANCH_ARGUMENTS[1]}

                                  SEMESTER="semester_${SEMESTER}"
                                  echo "SEMESTER=$(echo ${SEMESTER})" >> $GITHUB_ENV
                                  echo "CONSPECT_NAME=$(echo ${CONSPECT_NAME})" >> $GITHUB_ENV
                          id: extract_branch

                        - name: Build
                          uses: xu-cheng/latex-action@v2
                          env:
                                  CONSPECT_NAME: ${{ env.CONSPECT_NAME }}
                          with:
                                  root_file: main.tex
                                  working_directory: "${{ env.SEMESTER }}/${{ env.CONSPECT_NAME }}"
                                  args: -output-dir=../../../../raw_build -jobname=${{ env.CONSPECT_NAME }}
                                  compiler: pdflatex
                                  post_compile: "pdflatex -output-dir=$GITHUB_WORKSPACE/raw_build -jobname=$CONSPECT_NAME main.tex"
                         - name: 
                           uses: actions/upload-artifact@v2

                          with:

        # Это значение используется как ключ в хранилище

        name: my_doc

        # Путь до собранного pdf. Может содержать «*», «**»

        # Здесь это <working_directory>/<jobname>.pdf

        path: ${{ env.BRANCH_NAME}}/${{ env.CONSPECT_NAME}}.pdf
                      
                      
                      
                      
                      
                      
