#get targets (определяем директорию)
#prepare build (определяем аргументы директории, название итогового файла)
#build (компилируем ЛаТеХ)
#upload (загружаем обратно с нужным именем)

# "ИмяЛектора_Предмет_Семестр" !!!!!

name: Build and upload LaTeX
on:
    push:
        branches:
            - '!master'

jobs:
    TARGET = "semester_2/algebra_dyomin"
    CONSPECT_NAME="Dyomin_Algebra_2"
    
    build:
           runs-on: ubuntu-latest
            steps:    
                - uses: actions/checkout@v2
                - name: Build
                          uses: xu-cheng/latex-action@v2
                          with:
                                  root_file: main.tex
                                  working_directory: $TARGET
                                  args: -jobname=$CONSPECT_NAME -pdf -file-line-error -halt-on-error -interaction=nonstopmode
                                  compiler: pdflatex  
                 - name: upload file
                           uses: actions/upload-artifact@v2
                           with:
                                name: $CONSPECT_NAME
                                path: $TARGET/$CONSPECT_NAME.pdf
